# -*- coding: utf-8 -*-
"""content_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0_p_YC5adeNhXX-P8YrZg7aX9hF0dm1
"""

import os
import time
import numpy as np
import faiss
from pymongo import MongoClient
from dotenv import load_dotenv
from bson import ObjectId
load_dotenv()

from config import MONGO_URI
client = MongoClient(MONGO_URI)
print("Mongo connected successfully")

ml_db = client["ml_recommendation"]
user_activity_col = client["user_management"]["user_activity"]

# Load projected item embeddings
docs = list(ml_db["item_embeddings"].find({}, {"_id": 0}))

post_ids = [doc["postId"] for doc in docs]
item_vectors = np.array(
    [doc["item_embedding"] for doc in docs],
    dtype="float32"
)

faiss.normalize_L2(item_vectors)

index = faiss.IndexFlatIP(item_vectors.shape[1])
index.add(item_vectors)

postid_to_idx = {pid: i for i, pid in enumerate(post_ids)}

def recommend_for_user_full(user_id, top_k=100):
    start = time.time()

    doc = user_activity_col.find_one({"userId": ObjectId(user_id)})
    if not doc:
        return {"error": "User not found"}

    liked_posts = []
    for item in doc.get("likes", []):
        pid = str(item.get("postId"))
        if pid in postid_to_idx:
            liked_posts.append(pid)

    if not liked_posts:
        return {"error": "No interactions"}

    idxs = [postid_to_idx[pid] for pid in liked_posts]
    user_profile = item_vectors[idxs].mean(axis=0, keepdims=True)

    faiss.normalize_L2(user_profile)

    D, I = index.search(user_profile, top_k)

    results = [post_ids[i] for i in I[0]]

    return {
        "user_id": str(user_id),  
        "final_posts": results,
        "time": time.time() - start
    }

